---
- name: Create values file
  template:
    src: rustfs-values.j2
    dest: /tmp/rustfs-values.yaml

- name: Add RustFS helm repo
  command: helm repo add rustfs https://charts.rustfs.com
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: "Update helm repositories"
  command: helm repo update
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
    
- name: Create rustfs namespace
  block:
    - copy: src=rustfs-namespace.yaml dest=/tmp/rustfs-namespace.yaml
    - command: kubectl apply -f /tmp/rustfs-namespace.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

- name: Install (or upgrade) the chart
  command: helm upgrade rustfs --install rustfs/rustfs --namespace rustfs --create-namespace --values /tmp/rustfs-values.yaml --version '1.0.0'
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: Create CORS middleware
  when: enable_httproute | bool
  block:
    - copy: src=middleware.yaml dest=/tmp/middleware.yaml
    - command: kubectl apply -f /tmp/middleware.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Add CORS middleware to the RustFS HTTPRoute
      command: kubectl patch httproute rustfs-route --namespace rustfs --type=json --patch '[{"op":"add","path":"/spec/rules/0/filters","value":[{"extensionRef":{"group":"traefik.io","kind":"Middleware","name":"cors-allow-all"},"type":"ExtensionRef"}]}]'
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

- name: Download RustFS Client binary
  unarchive:
    src: https://github.com/rustfs/cli/releases/download/v{{ rustfs_cli_version }}/rustfs-cli-linux-amd64-gnu-v{{ rustfs_cli_version }}.tar.gz
    dest: /usr/local/bin
    remote_src: true
    include:
      - rc
    mode: '0755'
    creates: /usr/local/bin/rc
